import urllib3

class ContentType:
    def __str__(self) -> str: ...
    def charset(self, default: str = 'UTF-8') -> str: ...
    def is_json(self) -> bool: ...
    @classmethod
    def from_response(cls, response: urllib3.response.HTTPResponse) -> ContentType: ...


class WebLinkHeader:
    @classmethod
    def from_value(cls, value: str) -> WebLinkHeader: ...
    @classmethod
    def from_response(cls, response: urllib3.response.HTTPResponse) -> WebLinkHeader: ...
